### ISSUE TITLE
Error thrown when customer_uuid_expiration date is in the past

### ISSUE THREAD

**Issue by joecoolio66** [sezzle/sezzle-prestashop#1]
I was contacted by a customer who was getting this error from the sezzle module at checkout before the sezzle checkout redirection:

Unexpected Error Processing Sezzle.  Please try again.

While checking the logs, he was getting the following error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_customer' in 'where clause'

Upon investigating further, it appears this happens randomly and has been happening since we installed the sezzle module.

I tracked the SQL query to this block in the SezzleTokenization.php:

public static function getByCustomerId($customerId)
    {
        $sql = new DbQuery();
        $sql->select(self::$definition['primary'])
            ->from(self::$definition['table'])
            ->where('id_customer = ' . (int)$customerId)
            ->orderBy(self::$definition['primary'] . " DESC");
        $idSezzleTokenization = Db::getInstance()->getValue($sql);
        return new self($idSezzleTokenization);
    }

The table in question here was the sezzle_tokenization table

Upon looking up his customer id in this table, I realized that the customer_uuid_expiration date was less than today's date.  Once I delete this row, the error went away.  

Please look into this... in the meantime we will have to keep maintenance on this table.

**Comment by arijit-sezzle** [comment]
This should be fixed in v2.0.7.

**Comment by joecoolio66** [comment]
Hi there,

Will the sezzle prestashop module be updated for use with Prestashop 9?  
If so, what will the timeline be?  Thanks

**Comment by joecoolio66** [comment]
Just following up on this.  If the sezzle module is not updated to be 
able to be used with the latest version of prestashop we will no longer 
be able to use it as an option for our customers.
